Trade_Invitation, Dear *WHO*,<p>\r\n\r\nAs an existing trader of *FESTIVAL*, you are being given an advance opportunity to book a pitch for *PLANYEAR* before we open trade applications publicly.  <p>\r\n\r\nThe dates of next year's festival are *DATES*.<p>\r\n\r\nThe location you are being offered is *LOCATION* at a price of *PRICE*.<p>\r\n\r\nIf you wish to accept the offer of a pitch at the quoted price, go to your personal *LINK* and click the purple <b>Accept</b> button near the bottom of the page.<p>\r\n\r\nYou will be asked to pay your deposit and details of how to pay will appear on screen and in your confirmation email.<p>\r\n\r\nOnce your deposit payment has been received, we will issue an invoice confirming that your pitch is secure pending your balancing payment.<p>\r\n\r\nLater we will issue a reminder that your balancing payment of &pound;*BALANCE* is due. Once your payment has arrived, we will issue an invoice confirming that your pitch is fully secure.<P>\r\n\r\nIf you wish to decline this offer, please click on your personal link and click 'decline'. <p>\r\n\r\nIf you are no longer trading, or no longer wish to be notified about trade stands at the festival click *REMOVE*.<p>\r\n\r\nPlease use this personal *LINK* to directly upload a photo of your stand/products and to write about what you sell.<p>\r\n\r\nYou can also use this link to add/correct details about your business, contact information, or change your pitch(es), update your insurance and risk assessment etc.<p>\r\n\r\nPhotos and descriptions of your goods may be visible to the public. Personal information can only be seen by the festival committee.<p> \r\n\r\nDetails of your pitch number, general trader information and particulars of setup and clear down information will appear later and be visible through the link.<p>\r\n\r\nSave the link for future use.  If you lose or forget it you will be able to request a new personal link from the website (as soon as trade applications go public).<p>\r\n\r\nIf you have any queries that are not answered by the *WEB:int/TradeFAQ.php:Trade_FAQ*, please contact *MAILTO_trade*.<p>\r\n\r\nVery much looking forward to seeing you again.<p>  \r\n\r\nWith best wishes from the *FESTIVAL* Team.
Trade_Partial_Payment, *WHO*,<p>\r\n\r\nThank you for paying some of your pitch fee.<p>\r\n\r\nPlease pay the rest.<p>\r\n\r\n*DETAILS*\r\n\r\nWith best wishes from the *FESTIVAL* Team.
Trade_Open, *WHO*,<p>\r\n  \r\nTrade stand booking for the *FESTIVAL* in *PLANYEAR* is now open.<p>\r\n\r\nPlease use this personal *LINK* to directly add and/or correct details about your business, contact information,\r\nyour product descriptions, book or change your pitch(es) and update your\r\nInsurance and Risk Assessment etc.<p>\r\n  \r\nDetails of your pitch location, general trader information and particulars of setup and cleardown\r\ninformation will also appear through the link.<p> \r\n    \r\nSave the link for future use.  If you lose or forget it you will be able to request a new personal link\r\nfrom the website (as soon as trade appliactions go public).<p>\r\n  \r\nIf you have any queries that are not answered by the *WEB:int/TradeFAQ.php:Trade_FAQ*,\r\nplease contact *MAILTO_trade*.<p>\r\n  \r\nIf you are no longer trading, or no longer wish to be notified about trade stands at the festival click *REMOVE*.<p>\r\n\r\nWith best wishes from the *FESTIVAL* Team.
Trade_Link, *WHO*,<p>\r\n\r\nPlease use this *LINK*.<p>\r\n\r\nTo add/correct details about your business, contact information, your product descriptions and pitch\r\nupdate your Insurance and Risk Assessment etc.<p>\r\n\r\nDetails of your pitch location, general trader information and particulars of setup and clear down information will also appear there.<p>\r\n\r\nSave the link for future use.<p>\r\n\r\nWith best wishes from the *FESTIVAL* Team.
Trade_Submit, *WHO*,<p>\r\n\r\nThankyou for submitting your application for Trading at the *FESTIVAL* in *PLANYEAR*.<p>\r\n\r\nPlease use this *LINK* to add/correct details about your business, contact information, your product descriptions, book or change your pitch(es) and update your Insurance and Risk Assessment etc.<p> \r\n\r\nDetails of your pitch location, general trader information and particulars of setup and clear down information will also appear there.<p>\r\nSave the link for future use.<p>\r\n\r\nIf you have any queries that are not answered by the *WEB:int/TradeFAQ.php:Trade_FAQ*,\r\nplease contact *MAILTO_trade*<p>\r\n\r\n*DETAILS*\r\n\r\nWith best wishes from the *FESTIVAL* Team.
Trade_InvitationBetter, *WHO*,<p>\r\n\r\nAs one of last year's traders at *FESTIVAL*, you're being given an advance opportunity to book a pitch this for *PLANYEAR* before we open booking to everyone.  <p>\r\n\r\nThe location we originally gave you last year was an area we hadn't previously used for trade stands, and was offered at a low price because it was an unknown.  The  offer we are making here is for the area you were moved to on Sunday, but the price is the price is the price for the new area and hence will be higher than the rate you paid last year.<p>\r\n\r\nThe dates are *DATES*.<p>\r\n\r\nThe location you are being offered is *LOCATION* at a price of *PRICE*.<p>\r\n\r\nIf you wish to accept the offer of a pitch at the quoted price, go to your personal *LINK* and click <b>Accept</b>.<p>\r\n\r\nYou will then be asked to pay your deposit - details of how to pay will appear on screen and in your confirmation email.<p>\r\n\r\nAn invoice saying paid will be sent a few days after you have paid (when it has been processed).<p>\r\n\r\nLater you will receive a second invoice to pay the balance of &pound;*BALANCE*.<P>\r\n\r\nIf you wish to decline the offer, please click on your personal link and click 'decline'. <p>\r\n\r\nIf you are no longer trading, or no longer wish to be notified about trade stands at the festival click *REMOVE*.<p>\r\n  \r\nThis year, we will be featuring all our traders on our web site.\r\n\r\nPlease use this personal *LINK* to directly upload a photo of your stand/products and to write about what you sell.<p>\r\n\r\nYou can also use this link to add/correct details about your business, contact information, or change your pitch(es) , update your Insurance and Risk Assessment etc.<p>\r\n\r\nPhotos and descriptions of your goods will be visible to the public. Personal information can only be seen by the festival committee.<p>  \r\n  \r\nDetails of your pitch number, general trader information and particulars of setup and clear down\r\ninformation will  appear later and be visible through the link.<p>\r\n\r\nSave the link for future use.  If you lose or forget it you will be able to request a new personal link\r\nfrom the website (as soon as trade applications go public).<p>\r\n\r\nIf you have any queries that are not answered by the *WEB:int/TradeFAQ.php:Trade_FAQ*,\r\nplease contact *MAILTO_trade*.<p>\r\n\r\nWith best wishes from the *FESTIVAL* Team.
Login_Welcome, *WHO*,<p>\r\n\r\nWelcome to the *FESTIVAL* staff pages.<p>\r\n\r\nIt is initially accessed by using the *WEB:int/Login.php:Staff_Login* at the bottom of any page below the copyright statement on any page of the *WEB*.<p>\r\n\r\nYour username is : *USER*<br>\r\nInitial password : *PWD*<p>
Trade_AcceptNoDeposit, *WHO*,<p>\r\n\r\nThis is to confirm that you have accepted our offer to trade at *FESTIVAL* in *PLANYEAR*.<p>\r\n\r\nThe trade address *MAILTO_trade*<p> \r\n\r\nPlease use this *LINK* to add/correct details about your business, contact information, your product descriptions, book or change your pitch(es) and  update your Insurance and Risk Assessment etc.<p> \r\n\r\nDetails of your pitch location, general trader information and particulars of setup and clear down information will also appear there.<p>\r\n\r\n<b>Save the link for future use.</b><p>\r\n\r\n*DETAILS*\r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n
Trade_Cancel, *WHO*,<p>\r\n\r\nThis is to record that your application for trading at *FESTIVAL* in *PLANYEAR* has been cancelled.<p>\r\n\r\nIf this is in error please contact *MAILTO_trade*.<p>\r\n\r\nYou may use your *LINK* to apply again in the future.<p>\r\n\r\nIf you are no longer trading, or no longer wish to be notified about trade stands at the festival click *REMOVE*.<p>\r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n\r\n
Trade_Hold, *WHO*,<p>\r\n\r\nYour application to trade at the *FESTIVAL* in *PLANYEAR*, is being held on the wait list. <p>\r\n\r\nif space is found we hope to offer you a pitch.<p>\r\n\r\nPlease use this *LINK* to add/correct details about your business, contact information, your product descriptions, book or change your pitch(es) and give\r\npower requirements, update your Insurance and Risk Assessment etc.<p> \r\n\r\nIf you have any queries that are not answered by the *WEB:int/TradeFAQ.php:Trade_FAQ*,\r\nplease contact *MAILTO_trade*<p>\r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n
Trade_Decline, *WHO*,<p>\r\n\r\nThis is to inform you that your application for trading at *FESTIVAL* in *PLANYEAR* has been declined.<p>\r\n\r\nYou may use your *LINK* to apply again in the future.<p>\r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n
Trade_Changes, Hi,\r\n\r\nThe Trader below has changed their requirements, and will need to be quoted a new fee.<p>\r\n\r\nDirect link to that trader *FESTLINK* (you need to be logged in for this to work)<p>\r\n\r\n*DETAILS*
Trade_UpdateBalance, Hi,<p>\r\n\r\nThe Trader below has an updated Fee calculated, please note the change in the balance to &pound;*BALANCE*.\r\n\r\nDirect link to that trader *FESTLINK* (you need to be logged in for this to work)\r\n\r\n*DETAILS*
Trade_NewSubmit, Hi,<p>\r\n\r\nThe trader below has submitted an application, please either: decline, hold, or quote them a fee.<p>\r\n\r\nDirect link to that trader *FESTLINK* (you need to be logged in for this to work)\r\n\r\n*DETAILS*
Trade_Quote, *WHO*,<p>\r\n\r\nYou requested a trade stall pitch for the *PLANYEAR* *FESTIVAL* and we're pleased to say that we'd love to have you.<p>\r\n\r\nThe location you are being offered is *LOCATION* at a price of *PRICE*.<p>\r\n\r\nIf you wish to accept the offer of a pitch at the quoted price, go to your personal *LINK* and click the purple <b>Accept</b> button near the bottom of the page.<p>\r\n\r\nThe link can also be used to add/correct details about your business, contact information, your product descriptions, book or change your pitch(es) and  update your Insurance and Risk Assessment etc.<p> \r\n\r\nDetails of your pitch location, general trader information and particulars of setup and clear down information will also appear there.<p>\r\n\r\nSave the link for future use.<p>\r\n\r\nIf you have any queries that are not answered by the *WEB:int/TradeFAQ.php:Trade_FAQ*,\r\nplease contact *MAILTO_trade*<p>\r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n
Trade_Artisan_Invite, *COPY_Trade_Invitation*
Trade_Artisan_Accept, *COPY_Trade_Accept*
Login_Forgot_Password, *WHO*,<p>\r\n\r\nHere is a limited duration temporary *LINK* to set a new password (it will only work for a few hours).<p>
Stew_Application, *WHO*,<p>\r\n\r\nThank you for submitting your application for Volunteering and Stewarding.<p>\r\n\r\nIf you have any queries please contact *MAILTO_stewards*<p>\r\n\r\nThis is what you filled in.<p> \r\n\r\n*DETAILS*<p>\r\n
Stew_Paul, Hi,<p>\r\n\r\nApplication for Stewarding:<p>\r\n\r\n*DETAILS*<p>\r\n
Trade_Accepted_FullInvoice, *WHO*,<p>\r\n\r\nThis is to confirm that you have accepted our offer to trade at *FESTIVAL* in *PLANYEAR*.<p>\r\n\r\nAttached is an invoice for the full amount of *PRICE*, please pay this promptly to secure your pitch.<p>\r\n\r\nPlease use this *LINK* to add/correct details about your business, contact information, your product descriptions, book or change your pitch(es) and give\r\npower requirements, update your Insurance and Risk Assessment etc.<p> \r\n\r\nDetails of your pitch location, general trader information and particulars of setup and clear down information will also appear there.<p>\r\n\r\n<b>Save the link for future use.</b><p>\r\n\r\n*DETAILS*\r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n
Vol_Link_Message, *WHO*,<p>\r\n\r\nYou are recorded as a Volunteer for *FESTIVAL*.<p>\r\n\r\nPlease use this *LINK*, to read/correct your details and to submit an application for this year's festival.<p>\r\n\r\nThank you very much.<p>\r\n\r\n\r\n
Trade_Accepted_Invoice, *WHO*,<p>\r\n\r\nThis is to confirm that you have accepted our offer to trade at*FESTIVAL* in *PLANYEAR*.<p>\r\n\r\nAttached is an invoice asking you to pay your deposit of &pound;*DEPOSIT* please pay within *PAYDAYS* days to secure your pitch.<p>\r\n\r\nLater you will receive a second invoice to pay the balance of &pound;*BALANCE*.<P>\r\n\r\n<p>Please use this *LINK* to add/correct details about your business, contact information, your product descriptions, book or change your pitch(es) and give\r\npower requirements, update your Insurance and Risk Assessment etc.<p> \r\n\r\nDetails of your pitch location, general trader information and particulars of setup and clear down information will also appear there.<p>\r\n\r\n<b>Save the link for future use.</b><p>\r\n\r\n*DETAILS*\r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n
Trade_Artisan_Accept_FullInvoice, *COPY_Trade_Accept_FullInvoice*
Trade_Artisan_Accept_Invoice, *COPY_Trade_Accept_Invoice*
Trade_Artisan_Final_Invoice, *COPY_Trade_Final_Invoice*
Trade_Cancel_Admin, Hi,<p>\r\n\r\nThe Trader below has cancelled.<p>\r\n\r\nDirect link to that trader *FESTLINK* (you need to be logged in for this to work)<p>\r\n\r\n*DETAILS*
Trade_Statement, *WHO*,<p>\r\n\r\nThis is a statement of your application's status.<p>\r\n\r\nPlease use this *LINK*, to add/correct details about your business, contact information, your product descriptions, pitch and power requirements,\r\nupdate your Insurance and Risk Assessment etc.<p>\r\n\r\n*STATE*\r\n\r\n*TRADEMAP*\r\n\r\n*FINANCIAL*\r\n\r\n*DETAILS*\r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n\r\n
Trade_Final_Invoice, *WHO*,<p>\r\n\r\nAttached is the invoice for the balance of &pound;*BALANCE*, please pay this promptly to secure your pitch.<p>\r\n\r\n*TRADEMAP*<p>\r\n\r\n*WEBSITESTUFF*\r\n\r\nPlease use this *LINK* to add/correct details about your business, contact information, your product descriptions, book or change your pitch(es) and give\r\npower requirements, update your Insurance and Risk Assessment etc.<p> \r\n\r\nDetails of your pitch location, general trader information and particulars of setup and clear down information will also appear there.<p>\r\n\r\n<b>Save the link for future use.</b><p>\r\n\r\n*DETAILS*\r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n
Vol_Application_Submit, *WHO*,<p>\r\n\r\nThank you for submitting your application for Volunteering and Stewarding.<p>\r\n\r\nPlease use this *LINK*, to read/correct details about your application at anytime.<p>\r\n\r\nIf you have any queries please contact *MAILTO_volunteers*<p>\r\n\r\nThis is what you filled in.<p> \r\n\r\n*DETAILS*<p>\r\n\r\n\r\n\r\n
Vol_Application_Update, WHO*,<p>\r\n\r\nThank you for updating your application for Volunteering and Stewarding.<p>\r\n\r\nPlease use this *LINK*, to read/correct details about your application at anytime.<p>\r\n\r\nIf you have any queries please contact *MAILTO_volunteers*<p>\r\n\r\nThis is what you filled in.<p> \r\n\r\n*DETAILS*<p>\r\n\r\n
Vol_Staff_Submit, New application for Volunteering / Stewarding:<p>\r\n\r\nDirect link to that volunteer *FESTLINK* (you need to be logged in for this to work).<p>\r\n\r\n*DETAILS*<p>\r\n
Vol_Staff_Update, Updated application for Volunteering / Stewarding:<p>\r\n\r\nDirect link to that volunteer *FESTLINK* (you need to be logged in for this to work).<p>\r\n\r\n*DETAILS*<p>\r\n
Vol_Staff_NotThisYear, The Volunteer below, is no longer volunteering in *PLANYEAR*<p>\r\n\r\nThis is what they had previously submitted:<p>\r\n\r\n*DETAILS*<p>
Trade_Quote_WeekLeft, *WHO*,<p>\r\n\r\nYou have been quoted *PRICE* for a pitch in *LOCATION* at the  *PLANYEAR* *FESTIVAL*.<p>\r\n\r\nYou have 1 week left to use this *LINK* to accept the quote, after which this quote will be withdrawn and the space offered to other traders.\r\n\r\nShortly after accepting the offer, you will be sent an invoice for a deposit.  To secure the pitch, you must pay your deposit promptly.<p>\r\n\r\nIf you wish to decline the offer, please click on your personal *LINK* and click 'decline'. <p>\r\n\r\nIf you are no longer trading, or no longer wish to be notified about trade stands at the festival click *REMOVE*.<p>\r\n  \r\nThis year, we will be featuring all our traders on our web site.\r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n
Trade_Deposit_Paid_Invoice, Dear *WHO*,<p>\r\n\r\nThank you for paying your deposit for trading at *FESTIVAL* *PLANYEAR*. Your pitch space is secure pending your balancing payment.<p>\r\n\r\nYour deposit invoice is attached for your bookkeeping records.<p>\r\n\r\nLater we will issue a reminder that your balancing payment of &pound;*BALANCE* is due.<P>\r\n\r\n*DETAILS*<p>\r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n
Trade_Withdraw_Quote, *WHO*,<p>\r\n\r\nYour quote for a pitch in *LOCATION* at the  *PLANYEAR* *FESTIVAL* has been withdrawn.<p>\r\n\r\nYou may still submit an application, if you wish.<p>\r\n\r\nPlease use this *LINK* to add/correct details about your business, contact information, your product descriptions, book or change your pitch(es) and give\r\npower requirements, update your Insurance and Risk Assessment etc.<p> \r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n
Trade_UnQuote, *WHO*,<p>\r\n\r\nThe Quote for trading at *FESTIVAL* in *PLANYEAR* has now been withdrawn.<p>\r\n\r\nYou may use your *LINK* to submit an application again or in future years.<p>\r\n\r\nWith best wishes from the *FESTIVAL* Team.\r\n\r\n
Dance_Decide_Month, Hi, *WHO*,<p>\r\n\r\nLess than a month to go until the deadline for teams to register for the festival...<p>\r\n\r\nIf you're definitely <b>not coming:</b><p>\r\n\r\nPlease go to *LINK* and click 'Not coming'.  If you think you may be able to get a team for *NEXTYEAR*, then click\r\n'Not coming, please ask next year'.<p>\r\n\r\nIf you're <b>not yet certain</b> whether you have a team:<p>\r\n\r\nPlease go to *LINK* and click 'Possibly' and then update as soon as you know for certain.<p>\r\n\r\nIf you are <b>coming</b>:<p>\r\n\r\nPlease go to *LINK* and click 'Coming'.<p>\r\n\r\nSelect the days that you want to dance on, and tell us the earliest time and latest times you can perform. The\r\ndefaults are 10am to 5pm.<p>\r\n\r\nIf you'd like to do extra dance spots, just increase the number shown.<p>\r\n\r\nUpload your public liability insurance as soon as you have the certificate, and check the other information\r\nthat we have for your team.<p>\r\n\r\nFill in the number of performer's wristbands required, but remember you can update this number at any time\r\nuntil two weeks before the festival.<p>\r\n\r\nKind Regards,<p>\r\n\r\nDance organisers
Dance_Details, *WHO*,<p>\r\n\r\nWe are very pleased you are coming to *FESTIVAL* *PLANYEAR*. <p>\r\n\r\n*MISSING*\r\n\r\nKind Regards,<p>\r\n\r\nDance organisers
Dance_Program, *WHO*,<p>\r\n\r\nHere is the draft programme for *SIDE* for *FESTIVAL* *PLANYEAR*<p>\r\n\r\nPlease read and <span style='background:pink'>check this now</span> and if there are problems tell us within the week, any problem reported after that may or may not be fixable and may not get into the printed programme.<p>\r\n\r\n*PROG*<p>\r\n\r\n*MISSING*<p>\r\n\r\nKind Regards,<p>\r\n\r\nDance organisers<p>\r\n\r\nPS You can check your programme details at anytime by clicking on *LINK*, or by clicking on your team name on the *WEB*<p>
Finance_Default_Cover,  *WHO*,<p>\r\n\r\nAttached is your Invoice for:<p>\r\n\r\n*DETAILS*<p>\r\n\r\nMuch Regards,<p>\r\n\r\n*FESTIVAL*
Dance_Program_Check, *WHO*,<p>\r\n\r\nWe've been making good progress on reducing the number of our emails getting miss-identified as spam, but we know some are still failing to get through.  Hence, we are doing an extra check that all dancers have got their programme for *FESTIVAL* *PLANYEAR*<p>\r\n\r\nPlease click <span style='background:orange;padding:5;margin:5'><b>*TICKBOX:1:Programme_Seen*</b></span>  This will automatically tick the 'programme seen' box on your web record, and take you there in case you need to do anything else.<p>\r\n\r\nIf there are any problems with your dance spots, just send us an email asap and we'll do our best to fix any problems.<p>\r\n\r\n*PROG*<p>\r\n\r\n*MISSING*<p>\r\n\r\nKind Regards,<p>\r\n\r\nDance organisers<p>\r\n\r\nPS You can check your programme details at anytime by clicking on *LINK*, or by clicking on your team name on the *WEB:LineUp.php?T=Dance:Dance_lineup_page*<p>
Dance_Program_Revised, *WHO*,<p>\r\n\r\nHere is a <b>REVISED</b> programme for *SIDE* for *FESTIVAL* *PLANYEAR*, changes are minor, and in response to feedback from other teams<p>\r\n\r\nPlease read and <span style='background:pink'>check this now</span> and if there are problems tell us <b>NOW</b>.<p>\r\n\r\n*PROG*<p>\r\n\r\nAfter checking it, please <span style=background:pink><b>*TICKBOX:1:Click_This_Link*</b></span> to confirm receipt.<p>\r\n\r\n*MISSING*<p>\r\n\r\nKind Regards,<p>\r\n\r\nJDance organisers<p>\r\n\r\nPS You can check your programme details at anytime by clicking on *LINK*, or by clicking on your team name on the *WEB:LineUp.php?T=Dance:Dance_lineup_page*<p>
Dance_Final_Info, *WHO*,<p>\r\n\r\nPlease distribute this information around *SIDE*:<p>\r\n\r\n<p>\r\n\r\n*PROG*<p>\r\n\r\nKind Regards,<p>\r\n\r\nDance organisers
Dance_Invite, *WHO*,This needs Writing for your festival
Dance_Remind, *WHO*,\r\n\r\nWe had some issues with emails getting lost in spam filters, and we know that this year at least one email has already ended up in a spam filter. Hence, we're doing an extra check to make sure that all our invitations have arrived (obviously we don't expect you to know if you can come yet).\r\n\r\nIf you've already received an invitation from us for *FESTIVAL* *PLANYEAR*, please click <span style='background:yellow'>please could you *TICKBOX:Rec:click_this*  Invitation Seen</span>. This will automatically tick the 'invitation received' box on your web record, and take you there in case you want to edit anything else.\r\nYour web record is *LINK*.\r\n\r\nIf you haven't received an invitation, it would be much appreciated if you could check your spam folder and add 'dance@wimbornefolk.co.uk' to your address book so we can avoid emails getting lost in future. \r\n\r\nIf your invitation has completely vanished and isn't in the spam filter, let me know and I will resend it.\r\n\r\nMany thanks,\r\n\r\nDance Organisers
Trade_FinalPayment, Dear *WHO*,\r\n\r\nWith the *FESTIVAL* *PLANYEAR* fast approaching we would be grateful if you could please forward your balancing payment of &pound;*BALANCE*<p>.\r\n\r\n*PAYCODES*<p>\r\n\r\nWe kindly ask that you pay promptly on order to secure your pitch. For your bookkeeping records, we will issue an invoice to you within 48 hours of receipt of your payment.<p>\r\n\r\n*TRADEMAP*<p>\r\n\r\n*WEBSITESTUFF*\r\n\r\nPlease use this *LINK* to add/correct details about your business, contact information, your product descriptions, book or change your pitch(es) and update your Insurance and Risk Assessment etc.<p>\r\n\r\nDetails of your pitch location, general trader information and particulars of setup and clear down information will also appear there.<p>\r\n\r\n<b>Save the link for future use.</b><p> \r\n\r\n*DETAILS*\r\n\r\nWith best wishes from the *FESTIVAL* Team.
Trade_Fully_Paid_Invoice, Dear *WHO*,<p>\r\n\r\n \r\n\r\nThank you for your payment. Your pitch at *FESTIVAL* *PLANYEAR* is now fully secure.<p>\r\n\r\nYour invoice is attached for your bookkeeping records.<p>\r\n\r\n*TRADEMAP*<p>\r\n\r\n*WEBSITESTUFF*\r\n\r\nPlease use this *LINK* to add/correct details about your business, contact information, your product descriptions, book or change your pitch(es) and update your Insurance and Risk Assessment etc.<p> \r\n\r\nDetails of your pitch location, general trader information and particulars of setup and clear down information will also appear there.<p> \r\n\r\n<b>Save the link for future use.</b><p> \r\n\r\n*DETAILS*\r\n\r\nWith best wishes from the *FESTIVAL* Team.
Trade_Accepted_FullPayment, *WHO*,<p>\r\n\r\nThis is to confirm that you have accepted our offer to trade at *FESTIVAL* in *THISYEAR*.<p>\r\n\r\nPlease now pay your full fees of &pound;*PRICE* (it is too late to just pay a deposit).   You will be sent an invoice for this once it has been paid (it may take a couple of days).<p>\r\n\r\n*PAYCODES*\r\n\r\nPlease use this *LINK* to add/correct details about your business, contact information, your product descriptions, book or change your pitch(es) and update your Insurance and Risk Assessment etc.<p> \r\n\r\nDetails of your pitch location, general trader information and particulars of setup and clear down information will also appear there.<p>\r\n\r\n<b>Save the link for future use.</b><p>\r\n\r\n*DETAILS*\r\n\r\nWith best wishes from the *FESTIVAL* Team.
Trade_Accepted_DepositPayment, Dear *WHO*,<p>\r\n\r\nThis is to confirm that you have accepted our offer to trade at *FESTIVAL* in *PLANYEAR*.<p>\r\n\r\nIn order to secure your pitch we kindly request that you now pay your deposit of &pound;*DEPOSIT*. For your bookkeeping records, we will issue an invoice to you within 48 hours of receipt of your payment.<p>\r\n\r\n*PAYCODES*<p>\r\n\r\nLater you will be asked to pay the balance of &pound;*BALANCE*.<P>\r\n\r\nPlease use this *LINK* to add/correct details about your business, contact information, your product descriptions, book or change your pitch(es) and give power requirements, update your insurance and risk assessment etc.<p>\r\n\r\nDetails of your pitch location, general trader information and particulars of setup and clear down information will also appear there.<p>\r\n\r\n<b>Save the link for future use.</b><p>\r\n\r\n*DETAILS*\r\n\r\nWith best wishes from the *FESTIVAL* Team.

