<?php
  include_once("fest.php");
  A_Check('Committee','Finance');

  dostaffhead("Manage Budget Items");

/* List all budget areas for year, if current allow edits, if historical not.
   Add Items, change items etc 
   Aimed for Treasurer/Me to update ONLY.  
   
   No user control to budgets YET think sections, think people, think...
   
   There is a much simpler BudgetView for lesser committee members
*/

  include_once("BudgetLib.php");
  global $YEAR,$PLANYEAR;

  $Budget = Get_Budget();
  echo "<h2>Manage Budget - $YEAR</h2>\n";
  if (UpdateMany('BudgetAreas','Put_BudgetItem',$Budget)) $Budget = Get_Budget();

  echo "Do not edit the <b>Used So Far</b> column - it will be autogenerated<p>\n";
  $coln = 0;
  echo "<form method=post action=BudgetManage.php>";
  echo fm_hidden('Y',$YEAR);
  echo fm_hidden('Year0',$PLANYEAR);
  echo "<table id=indextable border>\n";
  echo "<thead><tr>";
  echo "<th><a href=javascript:SortTable(" . $coln++ . ",'N')>Id</a>\n";
  echo "<th><a href=javascript:SortTable(" . $coln++ . ",'T')>Name</a>\n";
  echo "<th><a href=javascript:SortTable(" . $coln++ . ",'N')>Budget</a>\n";
  echo "<th><a href=javascript:SortTable(" . $coln++ . ",'N')>Used So Far</a>\n";
  /*
  echo "<th><a href=javascript:SortTable(" . $coln++ . ",'T')>Who</a>\n";
  echo "<th><a href=javascript:SortTable(" . $coln++ . ",'T')>Who 2</a>\n";
  echo "<th><a href=javascript:SortTable(" . $coln++ . ",'T')>Who 3</a>\n";
  echo "<th><a href=javascript:SortTable(" . $coln++ . ",'T')>Who 4</a>\n";
*/
  echo "</thead><tbody>";
  foreach($Budget as $b) {
    $i = $b['id'];
    echo "<tr><td>$i";
    echo fm_text1("",$g,'SName',1,'','',"SName$i") . "</a>";
    echo fm_text1("",$g,'Budget',1,'','',"Budget$i") . "</a>";
    echo fm_text1("",$g,'CommittedSoFar',1,'','',"CommittedSoFar$i") . "</a>";
    echo fm_number1("",$g,'RelOrder','','',"RelOrder$i") . "</a>";
    echo "<td><img src='" . $g['File'] . "' height=75>";
    echo "\n";
  }
  if ($YEAR == $PLANYEAR) {
    echo "<tr><td><td><input type=text name=SName0 >";
    echo "<td><input type=text name=Captions0 >";
    echo "<td><input type=number name=RelOrder0 >";

  }
  echo "</table>\n";
  echo "<input type=submit name=Update value=Update>\n";
  echo "</form></div>";
  echo "<h2><a href=BudgetView.php>Budget View</a>, <a href=BudgetManage.php?ACTION=RESCAN>Re scan (Not Yet)</a></h2><p>\n";

  dotail();

?>
