CREATE TABLE `Trade` (
  `Tid` int(11) NOT NULL AUTO_INCREMENT,
  `SN` text,
  `Status` tinyint(4) NOT NULL,
  `Contact` text NOT NULL,
  `Email` text NOT NULL,
  `Website` text NOT NULL,
  `ListMe` tinyint(4) NOT NULL,
  `Photo` text NOT NULL,
  `GoodsDesc` text NOT NULL,
  `Phone` text NOT NULL,
  `Mobile` text NOT NULL,
  `TradeType` tinyint(4) NOT NULL,
  `Charity` text NOT NULL,
  `BID` tinyint(4) NOT NULL,
  `ChamberTrade` tinyint(4) NOT NULL,
  `Previous` tinyint(4) NOT NULL,
  `RefCode` text NOT NULL,
  `Address` text NOT NULL,
  `PostCode` text NOT NULL,
  `Notes` text NOT NULL,
  `AccessKey` text NOT NULL,
  `PublicHealth` text NOT NULL,
  `SageCode` text NOT NULL,
  PRIMARY KEY (`Tid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
