CREATE TABLE `Volunteers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `SN` text,
  `Email` text NOT NULL,
  `Phone` text NOT NULL,
  `Address` text NOT NULL,
  `PostCode` text NOT NULL,
  `Birthday` text NOT NULL,
  `ContactName` text NOT NULL,
  `ContactPhone` text NOT NULL,
  `SC_Stewarding` tinyint(4) NOT NULL,
  `SC_Setup` tinyint(4) NOT NULL,
  `SC_Technical` tinyint(4) NOT NULL,
  `SC_Artistic` tinyint(4) NOT NULL,
  `SC_Media` tinyint(4) NOT NULL,
  `Prefer` text NOT NULL,
  `Dislike` text NOT NULL,
  `AvailBefore` text NOT NULL,
  `AvailWed` text NOT NULL,
  `AvailThu` text NOT NULL,
  `AvailFri` text NOT NULL,
  `AvailSat` text NOT NULL,
  `AvailSun` text NOT NULL,
  `AvailMon` text NOT NULL,
  `AvailTue` text NOT NULL,
  `DBS` text NOT NULL,
  `Relation` smallint(6) NOT NULL,
  `Year` int(11) NOT NULL,
  `AccessKey` text NOT NULL,
  `OtherText` text NOT NULL,
  `Notes` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
