CREATE TABLE `Invoices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `State` tinyint(4) NOT NULL,
  `BZ` text,
  `Contact` text,
  `Email` text NOT NULL,
  `Phone` text NOT NULL,
  `Mobile` text NOT NULL,
  `Address` text NOT NULL,
  `PostCode` text NOT NULL,
  `IssueDate` int(11) NOT NULL,
  `EmailDate` int(11) NOT NULL,
  `DueDate` int(11) NOT NULL,
  `PayDate` int(11) NOT NULL,
  `InvoiceCode` int(11) NOT NULL,
  `InvoiceCode2` int(11) NOT NULL,
  `InvoiceCode3` int(11) NOT NULL,
  `OurRef` text NOT NULL,
  `YourRef` text NOT NULL,
  `Total` int(11) NOT NULL,
  `PaidTotal` int(11) NOT NULL,
  `Desc1` text NOT NULL,
  `Amount1` int(11) NOT NULL,
  `Desc2` text NOT NULL,
  `Amount2` int(11) NOT NULL,
  `Desc3` text NOT NULL,
  `Amount3` int(11) NOT NULL,
  `Source` int(11) NOT NULL,
  `History` text NOT NULL,
  `Year` int(11) NOT NULL,
  `SourceId` int(11) NOT NULL,
  `Reason` text NOT NULL,
  `CNReason` text NOT NULL,
  `Revision` int(11) NOT NULL,
  `CoverNote` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
