CREATE TABLE `OtherPart` (
  `OtherId` int(11) NOT NULL AUTO_INCREMENT,
  `SN` text,
  `ShortName` text NOT NULL,
  `Type` text NOT NULL,
  `Importance` int(11) NOT NULL,
  `Blurb` text NOT NULL,
  `Email` text NOT NULL,
  `Contact` text NOT NULL,
  `Phone` text NOT NULL,
  `Mobile` text NOT NULL,
  `Address` text NOT NULL,
  `Postcode` text NOT NULL,
  `AltContact` text NOT NULL,
  `AltEmail` text NOT NULL,
  `AltPhone` text NOT NULL,
  `AltMobile` text NOT NULL,
  `Notes` text NOT NULL,
  `Description` text NOT NULL,
  `Website` text NOT NULL,
  `Website2` text NOT NULL,
  `Facebook` text NOT NULL,
  `Twitter` text NOT NULL,
  `Instagram` text NOT NULL,
  `Photo` text NOT NULL,
  `Video` text NOT NULL,
  `OtherStatus` tinyint(4) NOT NULL,
  `Insurance` tinyint(4) NOT NULL,
  `AccessKey` text NOT NULL,
  PRIMARY KEY (`OtherId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
